import { Hairstyle } from '../models/Hairstyle';
import { getHairstyleImage } from '../data/hairstyleImages';
import logger from '../utils/logger';

const DEFAULT_IMAGE = 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=300&h=300&fit=crop&crop=face';

const hairstyleDefs = [
  { name: 'Buzz Cut', slug: 'buzz-cut', category: 'men' as const, gender: 'male' as const, prompt: 'A person with a very short buzzed haircut, clippershaved head' },
  { name: 'Low Fade', slug: 'low-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Modern low fade haircut with short textured top' },
  { name: 'Mid Fade', slug: 'mid-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Mid skin fade haircut with longer top' },
  { name: 'High Fade', slug: 'high-fade', category: 'men' as const, gender: 'male' as const, prompt: 'High skin fade with textured top' },
  { name: 'Taper Fade', slug: 'taper-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Gradual taper fade haircut' },
  { name: 'Afro', slug: 'afro', category: 'men' as const, gender: 'male' as const, prompt: 'Full voluminous afro hairstyle' },
  { name: 'Twists', slug: 'twists', category: 'men' as const, gender: 'male' as const, prompt: 'Neat two strand twists hairstyle' },
  { name: 'Dreadlocks', slug: 'dreadlocks', category: 'men' as const, gender: 'male' as const, prompt: 'Long natural dreadlocks hairstyle' },
  { name: 'Mullet', slug: 'mullet', category: 'men' as const, gender: 'male' as const, prompt: 'Modern mullet haircut business in front party in back' },
  { name: 'Undercut', slug: 'undercut', category: 'men' as const, gender: 'male' as const, prompt: 'Undercut with long hair on top and shaved sides' },
  { name: 'Mohawk', slug: 'mohawk', category: 'men' as const, gender: 'male' as const, prompt: 'Bold mohawk with shaved sides' },
  { name: 'Pompadour', slug: 'pompadour', category: 'men' as const, gender: 'male' as const, prompt: 'Classic pompadour with voluminous swept back hair' },
  { name: 'Quiff', slug: 'quiff', category: 'men' as const, gender: 'male' as const, prompt: 'Modern quiff with volume and fade' },
  { name: 'Side Part', slug: 'side-part', category: 'men' as const, gender: 'male' as const, prompt: 'Clean side part haircut professional style' },
  { name: 'Crop Top', slug: 'crop-top', category: 'men' as const, gender: 'male' as const, prompt: 'Short crop top with textured fringe' },
  { name: 'Crew Cut', slug: 'crew-cut', category: 'men' as const, gender: 'male' as const, prompt: 'Classic crew cut tapered sides and back' },
  { name: 'Ivy League', slug: 'ivy-league', category: 'men' as const, gender: 'male' as const, prompt: 'Preppy ivy league haircut neat and clean' },
  { name: 'Caesar Cut', slug: 'caesar-cut', category: 'men' as const, gender: 'male' as const, prompt: 'Roman Caesar haircut with horizontal fringe' },
  { name: 'French Crop', slug: 'french-crop', category: 'men' as const, gender: 'male' as const, prompt: 'French crop with short fringe and faded sides' },
  { name: 'Temp Fade', slug: 'temp-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Sharp temple fade haircut' },
  { name: 'Burst Fade', slug: 'burst-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Burst fade semicircular fade around ears' },
  { name: 'Drop Fade', slug: 'drop-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Drop fade that curves behind the ear' },
  { name: 'Skin Fade', slug: 'skin-fade', category: 'men' as const, gender: 'male' as const, prompt: 'Skin fade down to bare skin sharpest fade' },
  { name: 'Fade with Design', slug: 'fade-with-design', category: 'men' as const, gender: 'male' as const, prompt: 'Fade haircut with shaved line design artistic hair tattoo' },
  { name: 'High Top Fade', slug: 'high-top-fade', category: 'men' as const, gender: 'male' as const, prompt: 'High top fade with flat top and faded sides' },
  { name: 'Flattop', slug: 'flattop', category: 'men' as const, gender: 'male' as const, prompt: 'Flattop haircut with sharp squared corners' },
  { name: 'Brush Cut', slug: 'brush-cut', category: 'men' as const, gender: 'male' as const, prompt: 'Brush cut short upright military style' },
  { name: 'Butch Cut', slug: 'butch-cut', category: 'men' as const, gender: 'male' as const, prompt: 'Uniformly short butch cut haircut' },
  { name: 'Slicked Back', slug: 'slicked-back', category: 'men' as const, gender: 'male' as const, prompt: 'Slicked back hair with glossy wet look' },
  { name: 'Man Bun', slug: 'man-bun', category: 'men' as const, gender: 'male' as const, prompt: 'Man bun long hair pulled back into a bun' },
  { name: 'Slick Back Undercut', slug: 'slick-back-undercut', category: 'men' as const, gender: 'male' as const, prompt: 'Slick back undercut combover style' },
  { name: 'Curtains', slug: 'curtains', category: 'men' as const, gender: 'male' as const, prompt: 'Curtain hairstyle with middle part and faceframing pieces' },
  { name: 'Bowl Cut', slug: 'bowl-cut', category: 'men' as const, gender: 'male' as const, prompt: 'Modern bowl cut Korean inspired round style' },
  { name: 'Korean Perm', slug: 'korean-perm', category: 'men' as const, gender: 'male' as const, prompt: 'Korean perm soft voluminous natural looking waves' },
  { name: 'Sponge Curls', slug: 'sponge-curls', category: 'men' as const, gender: 'male' as const, prompt: 'Sponge curls tight defined circular curls' },
  { name: 'Finger Coils', slug: 'finger-coils', category: 'men' as const, gender: 'male' as const, prompt: 'Finger coils defined spiral coils neat pattern' },
  { name: 'Jheri Curl', slug: 'jheri-curl', category: 'men' as const, gender: 'male' as const, prompt: 'Glossy wetlooking Jheri curl retro style' },
  { name: 'Liberty Spikes', slug: 'liberty-spikes', category: 'men' as const, gender: 'male' as const, prompt: 'Liberty spikes stiff upright spikes punk style' },
  { name: 'Fauxhawk', slug: 'fauxhawk', category: 'men' as const, gender: 'male' as const, prompt: 'Fauxhawk raised center strip without shaved sides' },
  { name: 'Death Hawk', slug: 'death-hawk', category: 'men' as const, gender: 'male' as const, prompt: 'Extreme deathhawk mohawk punk style' },
  { name: 'Psychobill', slug: 'psychobill', category: 'men' as const, gender: 'male' as const, prompt: 'Psychobilly pompadour with slicked back sides' },
  { name: 'Bob Cut', slug: 'bob-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Classic bob haircut chinlength straight hair' },
  { name: 'Pixie Cut', slug: 'pixie-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Short feminine pixie cut' },
  { name: 'Curly Bob', slug: 'curly-bob', category: 'women' as const, gender: 'female' as const, prompt: 'Curly bob haircut with bouncy voluminous curls' },
  { name: 'Wolf Cut', slug: 'wolf-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Shaggy wolf cut with layers and volume' },
  { name: 'Long Waves', slug: 'long-waves', category: 'women' as const, gender: 'female' as const, prompt: 'Long flowing beach waves soft natural wave pattern' },
  { name: 'Bangs', slug: 'bangs', category: 'women' as const, gender: 'female' as const, prompt: 'Straight across bangs with medium length hair' },
  { name: 'French Bob', slug: 'french-bob', category: 'women' as const, gender: 'female' as const, prompt: 'French bob jawlength blunt cut with bangs Parisian chic' },
  { name: 'Shag', slug: 'shag', category: 'women' as const, gender: 'female' as const, prompt: 'Layered shag haircut with feathered ends retro' },
  { name: 'Butterfly Cut', slug: 'butterfly-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Butterfly haircut long layered faceframing pieces' },
  { name: 'Hime Cut', slug: 'hime-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Hime cut long straight hair with blunt fringe and side pieces' },
  { name: 'Layered Long', slug: 'layered-long', category: 'women' as const, gender: 'female' as const, prompt: 'Long layered hair with cascading layers' },
  { name: 'V Cut', slug: 'v-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Long hair with Vshape at the back' },
  { name: 'U Cut', slug: 'u-cut', category: 'women' as const, gender: 'female' as const, prompt: 'Long hair with soft Ushape at the back' },
  { name: 'Bob with Bangs', slug: 'bob-with-bangs', category: 'women' as const, gender: 'female' as const, prompt: 'Bob haircut with straight across bangs' },
  { name: 'Lob', slug: 'lob', category: 'women' as const, gender: 'female' as const, prompt: 'Long bob lob haircut between chin and shoulders' },
  { name: 'Asymmetrical Bob', slug: 'asymmetrical-bob', category: 'women' as const, gender: 'female' as const, prompt: 'Asymmetrical bob shorter in back longer in front' },
  { name: 'Inverted Bob', slug: 'inverted-bob', category: 'women' as const, gender: 'female' as const, prompt: 'Inverted bob stacked layers in back wedge shape' },
  { name: 'Bixie', slug: 'bixie', category: 'women' as const, gender: 'female' as const, prompt: 'Bixie haircut hybrid of bob and pixie' },
  { name: 'Women Mullet', slug: 'mullet-women', category: 'women' as const, gender: 'female' as const, prompt: 'Modern feminine mullet feathered top longer back' },
  { name: 'Shullet', slug: 'shullet', category: 'women' as const, gender: 'female' as const, prompt: 'Shag mullet shullet hybrid with texture and layers' },
  { name: 'Curly Shag', slug: 'curly-shag', category: 'women' as const, gender: 'female' as const, prompt: 'Curly shag haircut layered for curly hair' },
  { name: 'Wavy Shag', slug: 'wavy-shag', category: 'women' as const, gender: 'female' as const, prompt: 'Wavy shag haircut textured beachy waves' },
  { name: 'Textured Bob', slug: 'textured-bob', category: 'women' as const, gender: 'female' as const, prompt: 'Textured bob with choppy layers and volume' },
  { name: 'Feathered Hair', slug: 'feathered-hair', category: 'women' as const, gender: 'female' as const, prompt: 'Feathered layered hair soft and airy Farrah Fawcett style' },
  { name: 'Pageboy', slug: 'pageboy', category: 'women' as const, gender: 'female' as const, prompt: 'Pageboy smooth helmet shaped bob turned under ends' },
  { name: 'Wedge', slug: 'wedge', category: 'women' as const, gender: 'female' as const, prompt: 'Wedge haircut triangular stacked back classic short' },
  { name: 'Pixie Bob', slug: 'pixie-bob', category: 'women' as const, gender: 'female' as const, prompt: 'Pixie bob hybrid short with longer faceframing pieces' },
  { name: 'Ombre Hair', slug: 'ombre-hair', category: 'women' as const, gender: 'female' as const, prompt: 'Ombre hair color fading from dark to light ends' },
  { name: 'Balayage', slug: 'balayage', category: 'women' as const, gender: 'female' as const, prompt: 'Balayage handpainted highlights sun-kissed natural' },
  { name: 'Half Up Half Down', slug: 'half-up-half-down', category: 'women' as const, gender: 'female' as const, prompt: 'Half up half down hairstyle versatile' },
  { name: 'Top Knot', slug: 'top-knot', category: 'women' as const, gender: 'female' as const, prompt: 'Top knot bun at crown of head sleek style' },
  { name: 'Low Bun', slug: 'low-bun', category: 'women' as const, gender: 'female' as const, prompt: 'Low bun at nape of neck elegant sophisticated' },
  { name: 'Messy Bun', slug: 'messy-bun', category: 'women' as const, gender: 'female' as const, prompt: 'Messy bun loosely gathered casual effortless' },
  { name: 'Sleek Ponytail', slug: 'sleek-ponytail', category: 'women' as const, gender: 'female' as const, prompt: 'Sleek high ponytail tightly pulled back polished' },
  { name: 'Low Ponytail', slug: 'low-ponytail', category: 'women' as const, gender: 'female' as const, prompt: 'Low ponytail sleek simple professional' },
  { name: 'Side Swept', slug: 'side-swept', category: 'women' as const, gender: 'female' as const, prompt: 'Side swept hair dramatically to one side elegant' },
  { name: 'Finger Waves', slug: 'finger-waves', category: 'women' as const, gender: 'female' as const, prompt: 'Finger waves sculpted Sshaped waves vintage 1920s' },
  { name: 'Victory Rolls', slug: 'victory-rolls', category: 'women' as const, gender: 'female' as const, prompt: 'Victory rolls pincurled rolls on top retro 1940s' },
  { name: 'Beehive', slug: 'beehive', category: 'women' as const, gender: 'female' as const, prompt: 'Beehive tall voluminous teased hairdo 1960s' },
  { name: 'Bubble Ponytail', slug: 'bubble-ponytail', category: 'women' as const, gender: 'female' as const, prompt: 'Bubble ponytail with hair bubble segments fun' },
  { name: 'Space Buns', slug: 'space-buns', category: 'women' as const, gender: 'female' as const, prompt: 'Space buns two buns on top of head playful' },
  { name: 'Bob with Highlights', slug: 'bob-with-highlights', category: 'women' as const, gender: 'female' as const, prompt: 'Bob haircut with blonde highlights dimension' },
  { name: 'Hair Keratin', slug: 'hair-keratin', category: 'women' as const, gender: 'female' as const, prompt: 'Keratin treated hair sleek smooth shiny straight' },
  { name: 'Perm Hair', slug: 'perm-hair', category: 'women' as const, gender: 'female' as const, prompt: 'Permed hair uniform curls chemical treatment' },
  { name: 'Japanese Straight', slug: 'japanese-straight', category: 'women' as const, gender: 'female' as const, prompt: 'Japanese straight perm perfectly pin-straight glossy hair' },
  { name: 'Digital Perm', slug: 'digital-perm', category: 'women' as const, gender: 'female' as const, prompt: 'Digital perm large soft waves hot rods' },
  { name: 'Setting Perm', slug: 'setting-perm', category: 'women' as const, gender: 'female' as const, prompt: 'Setting perm loose voluminous curls large rollers' },
  { name: 'Curly', slug: 'curly', category: 'unisex' as const, prompt: 'Naturally curly hair voluminous ringlets defined curls' },
  { name: 'Short Natural', slug: 'short-natural', category: 'unisex' as const, prompt: 'Short natural hair closecut textured tapered sides' },
  { name: 'Braids', slug: 'braids', category: 'unisex' as const, prompt: 'Neat cornrow or box braids symmetrical parting' },
  { name: 'Locs', slug: 'locs', category: 'unisex' as const, prompt: 'Well maintained locs hairstyle' },
  { name: 'Cornrows', slug: 'cornrows', category: 'unisex' as const, prompt: 'Cornrow braids woven close to scalp neat lines' },
  { name: 'Box Braids', slug: 'box-braids', category: 'unisex' as const, prompt: 'Box braids individual square sectioned braids' },
  { name: 'Knotless Braids', slug: 'knotless-braids', category: 'unisex' as const, prompt: 'Knotless braids without knots at root seamless' },
  { name: 'Fulani Braids', slug: 'fulani-braids', category: 'unisex' as const, prompt: 'Fulani braids cornrows front center part beads' },
  { name: 'French Braid', slug: 'french-braid', category: 'unisex' as const, prompt: 'French braids woven close to scalp from front' },
  { name: 'Dutch Braid', slug: 'dutch-braid', category: 'unisex' as const, prompt: 'Dutch braids reverse braids standing out' },
  { name: 'Fishtail Braid', slug: 'fishtail-braid', category: 'unisex' as const, prompt: 'Fishtail braid intricate woven romantic bohemian' },
  { name: 'Waterfall Braid', slug: 'waterfall-braid', category: 'unisex' as const, prompt: 'Waterfall braid cascading braid romantic' },
  { name: 'Passion Twists', slug: 'passion-twists', category: 'unisex' as const, prompt: 'Passion twists chunky twisted ropelike strands bohemian' },
  { name: 'Havana Twists', slug: 'havana-twists', category: 'unisex' as const, prompt: 'Havana twists thick chunky twist extensions bold' },
  { name: 'Spring Twists', slug: 'spring-twists', category: 'unisex' as const, prompt: 'Spring twists tightly coiled springy extensions' },
  { name: 'Senegalese Twists', slug: 'senegalese-twists', category: 'unisex' as const, prompt: 'Senegalese twists smooth sleek ropetwisted extensions' },
  { name: 'Marley Twists', slug: 'marley-twists', category: 'unisex' as const, prompt: 'Marley twists thick matte textured twisted natural' },
  { name: 'Kinky Twists', slug: 'kinky-twists', category: 'unisex' as const, prompt: 'Kinky twists textured twist extensions natural' },
  { name: 'Faux Locs', slug: 'faux-locs', category: 'unisex' as const, prompt: 'Faux locs artificial locs bohemian protective style' },
  { name: 'Distressed Locs', slug: 'distressed-locs', category: 'unisex' as const, prompt: 'Distressed locs roughened textured locs bohemian' },
  { name: 'Microlocs', slug: 'microlocs', category: 'unisex' as const, prompt: 'Microlocs very small thin locs neat uniform' },
  { name: 'Sisterlocks', slug: 'sisterlocks', category: 'unisex' as const, prompt: 'Sisterlocks very small uniform locks special pattern' },
  { name: 'Magic Locs', slug: 'magic-locs', category: 'unisex' as const, prompt: 'Magic locs curly faux locs wavy textured ends' },
  { name: 'Goddess Braids', slug: 'goddess-braids', category: 'unisex' as const, prompt: 'Goddess braids large chunky cornrow elegant patterns' },
  { name: 'Stitch Braids', slug: 'stitch-braids', category: 'unisex' as const, prompt: 'Stitch braids cornrows visible stitching pattern neat' },
  { name: 'Bantu Knots', slug: 'bantu-knots', category: 'unisex' as const, prompt: 'Bantu knots small coiled buns all over head' },
  { name: 'Flat Twists', slug: 'flat-twists', category: 'unisex' as const, prompt: 'Flat twists flat against scalp in neat rows' },
  { name: 'Mohawk Braid', slug: 'mohawk-braid', category: 'unisex' as const, prompt: 'Braided mohawk braid from forehead to nape bold' },
];

const hairstyles = hairstyleDefs.map((h) => ({
  ...h,
  previewImage: getHairstyleImage(h.slug) || DEFAULT_IMAGE,
  active: true as const,
}));

export const seedHairstyles = async () => {
  for (const data of hairstyles) {
    await Hairstyle.findOneAndUpdate(
      { slug: data.slug },
      { $setOnInsert: data },
      { upsert: true }
    );
  }
  logger.info(`Seeded ${hairstyles.length} hairstyles`);
};
